tap "homebrew/services"

brew "azure-cli"
brew "bash"
brew "cmatrix" # for fun
brew "coreutils" # for gnu tools
brew "curl"
brew "exa" # for ls
brew "gh"
brew "git-extras"
brew "git-sizer"
brew "gitup"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "go-task"
brew "grammarly-languageserver"
brew "hadolint"
brew "helm"
brew "htop"
brew "jq"
brew "node"
brew "pandoc"
brew "parallel" # for copying cloud images to azure storage
brew "pstree"
brew "rbenv"
brew "ripgrep"
brew "ruby"
brew "shellcheck"
brew "shunit2" # for testing shell scripts
brew "starship" # for shell prompt
brew "terminal-notifier"
brew "tfenv"
brew "tflint"
brew "tfsec"
brew "trash"
brew "tree"
brew "watch"
brew "yadm" # for dotfiles
brew "yamllint"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-lovers"
brew "zsh-syntax-highlighting"

tap "golangci/tap"
brew "golangci-lint"

tap "homebrew/cask-versions"
cask "alfred"
cask "cardhop"
cask "cloudflare-warp"
cask "grammarly"
cask "grammarly-desktop"
cask "hyper"
cask "keycastr"
cask "mactex"
cask "microsoft-outlook"
cask "microsoft-teams"
cask "microsoft-word"
cask "obsidian"
cask "openvpn-connect"
cask "podman-desktop"
cask "scapple"
cask "swiftdefaultappsprefpane"
cask "espanso"
cask "keycue"

tap "homebrew/cask-fonts"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-open-dyslexic"
cask "font-lato"
cask "font-rubik"

tap "homebrew/bundle"

# new items
brew "terraform-docs"
brew "driftctl"
brew "aztfexport"
cask "docker"
brew "markdownlint-cli"
brew "speedtest-cli"
cask "visual-studio-code"
brew "prettier"
