# frozen_string_literal: true

tap 'homebrew/cask-fonts'
tap 'homebrew/cask'
tap 'homebrew/services'

brew 'ansible-lint'
brew 'ansible'
brew 'antigen'
brew 'asciinema'
brew 'aspell'
brew 'aws-cfn-tools'
brew 'aws-iam-authenticator'
brew 'aws-shell'
brew 'awscli'
brew 'awslogs'
brew 'awsume'
brew 'bat'
brew 'black'
brew 'caddy'
brew 'cfn-flip'
brew 'cfn-format'
brew 'cfn-lint'
brew 'cfssl'
brew 'coreutils'
brew 'curl'
brew 'diction'
brew 'direnv'
brew 'docker-clean'
brew 'dos2unix'
brew 'ec2-api-tools'
brew 'editorconfig'
brew 'eksctl'
brew 'fd'
brew 'fdupes'
brew 'fx'
brew 'fzf'
brew 'gh'
brew 'ghostscript'
brew 'gist'
brew 'git-extras'
brew 'git-lfs'
brew 'git-quick-stats'
brew 'git-sizer'
brew 'git'
brew 'gitup'
brew 'gnupg'
brew 'go'
brew 'googler'
brew 'grafana'
brew 'graphviz'
brew 'hadolint'
brew 'helm'
brew 'helmfile'
brew 'highlight'
brew 'htop'
brew 'httpie'
brew 'httping'
brew 'httrack'
brew 'hunspell'
brew 'icdiff'
brew 'imagemagick'
brew 'imageoptim-cli'
brew 'influxdb'
brew 'jenv'
brew 'jid'
brew 'jpegoptim'
brew 'jq'
brew 'jsonlint'
brew 'jsonpp'
brew 'k6'
brew 'k9s'
brew 'kind'
brew 'krew'
brew 'kube-linter'
brew 'kubeaudit'
brew 'kubectx'
brew 'kubernetes-cli'
brew 'kustomize'
brew 'links'
brew 'lynx'
brew 'm-cli'
brew 'markdown'
brew 'markdownlint-cli'
brew 'mkcert'
brew 'mkdocs'
brew 'noti'
brew 'octant'
brew 'openapi-generator'
brew 'optipng'
brew 'osxutils'
brew 'pandoc-citeproc'
brew 'pandoc-crossref'
brew 'pandoc'
brew 'parallel'
brew 'pdftohtml'
brew 'prettier'
brew 'proselint'
brew 'pstree'
brew 'pwgen'
brew 'pyenv'
brew 'pylint'
brew 'rbenv-use'
brew 'rbenv'
brew 'restic'
brew 'ripgrep'
brew 'ruby'
brew 'scc'
brew 'shellcheck'
brew 'shfmt'
brew 'terraform_landscape'
brew 'terraform-docs'
brew 'terraform-inventory'
brew 'terraform'
brew 'terraformer'
brew 'terrahelp'
brew 'terrahub'
brew 'terrascan'
brew 'trash'
brew 'tree'
brew 'vale'
brew 'vegeta'
brew 'watch'
brew 'watchman'
brew 'wget'
brew 'yadm'
brew 'yamllint'
brew 'yarn'
brew 'yuicompressor'
brew 'zsh-completions'
brew 'zsh-lovers'
brew 'zsh'

tap 'atombender/ktail'
brew 'atombender/ktail/ktail'

tap 'aybabtme/tap'
brew 'aybabtme/tap/humanlog'

tap 'boz/repo'
brew 'boz/repo/kail'

tap 'cjbassi/gotop'
brew 'cjbassi/gotop/gotop'

tap 'derailed/popeye'
brew 'derailed/popeye/popeye'

tap 'gabrie30/utils'
brew 'gabrie30/utils/ghorg'

tap 'go-task/tap'
brew 'go-task/tap/go-task'

tap 'golangci/tap'
brew 'golangci/tap/golangci-lint'

tap 'goodwithtech/dockle'
brew 'goodwithtech/dockle/dockle'

tap 'hashicorp/tap'
brew 'hashicorp/tap/consul'
brew 'hashicorp/tap/nomad'
brew 'hashicorp/tap/packer'
brew 'hashicorp/tap/vault'
brew 'hashicorp/tap/waypoint'

tap 'instrumenta/instrumenta'
brew 'instrumenta/instrumenta/kubeval'

tap 'mveritym/mel'
brew 'mveritym/mel/kubedecode'

tap 'nektos/tap'
brew 'nektos/tap/act'

tap 'profclems/tap'
brew 'profclems/tap/glab'

tap 'rs/tap'
brew 'rs/tap/curlie'
brew 'rs/tap/dnstrace'
brew 'rs/tap/jaggr'
brew 'rs/tap/jplot'

tap 'tanishiking/jpp'
brew 'tanishiking/jpp/jpp'

tap 'wagoodman/dive'
brew 'wagoodman/dive/dive'

tap 'zaquestion/tap'
brew 'zaquestion/tap/lab'

tap 'xwmx/taps'
brew 'xwmx/taps/nb'

cask 'alfred'
cask 'bibdesk'
cask 'bunch'
cask 'cardhop'
cask 'cocoaspell'
cask 'coconutbattery'
cask 'controlplane'
cask 'docker'
cask 'drawio'
cask 'fantastical'
cask 'fliqlo'
cask 'font-fira-code'
cask 'font-open-dyslexic'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'
cask 'fuzzyclock'
cask 'google-cloud-sdk'
cask 'google-drive-file-stream'
cask 'gpg-suite-no-mail'
cask 'grammarly'
cask 'hazel'
cask 'hyper'
cask 'imageoptim'
cask 'karabiner-elements'
cask 'kextviewr'
cask 'keyboard-maestro'
cask 'keycastr'
cask 'keycue'
cask 'kindle'
cask 'launchcontrol'
cask 'launchrocket'
cask 'logos'
cask 'mactex'
cask 'marked'
# cask 'onyx'
cask 'openvpn-connect'
cask 'osxfuse'
cask 'paparazzi'
cask 'scapple'
cask 'screenflow'
cask 'scrivener'
cask 'shiftit'
cask 'slack'
cask 'thingsmacsandboxhelper'
cask 'vellum'
cask 'virtualbox-extension-pack'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'xquartz'
# cask 'zoom'
