# https://taskfile.dev
version: "3"
tasks:
  default:
    cmds:
    - softwareupdate --install --all
    - brew update
    - brew bundle --global
    - brew upgrade
    - brew autoremove
    - brew bundle cleanup --global
  check:
    cmds:
    - brew outdated
    - brew bundle cleanup --global
  clean:
    cmds:
    - brew autoremove
    - brew cleanup --prune=all
    - brew bundle cleanup --global --force
