# https://taskfile.dev
version: "3"
tasks:
  default:
    cmds:
      - task: update
      - task: bundle
      - task: upgrade
      - task: doctor
      - task: check

  system:
    cmds:
      - sudo softwareupdate --install --all --restart

  update:
    cmds:
      - brew update

  bundle:
    cmds:
      - brew bundle --global

  upgrade:
    cmds:
      - brew upgrade

  doctor:
    cmds:
      - brew doctor

  check:
    cmds:
      - brew bundle cleanup --global
      - brew bundle check --global

  outdated:
    cmds:
      - brew outdated

  clean:
    cmds:
    - brew autoremove
    - brew cleanup --prune=all
    - brew bundle cleanup --global --force
