# https://taskfile.dev
version: "3"
tasks:
  default:
    cmds:
      - softwareupdate --install --all
      - brew update
      - brew bundle --global
      - brew upgrade
      - brew bundle cleanup --global
    silent: true
  check:
    cmds:
      - brew outdated
      - brew bundle cleanup --global
    silent: true
  clean:
    cmds:
      - brew cleanup --prune=all
      - brew bundle cleanup --global --force
    silent: true
