# configuration
[directory]
truncation_length = 5
truncation_symbol = "…/"
[line_break]
disabled = true

# turn on
[kubernetes]
disabled = true
[memory_usage]
disabled = true
[shlvl]
disabled = false
[status]
disabled = false

# turn off
[aws]
disabled = true
[conda]
disabled = true
[crystal]
disabled = true
[dart]
disabled = true
[dotnet]
disabled = true
[gcloud]
disabled = true
[elixer]
disabled = true
[elm]
disabled = true
[erlang]
disabled = true
[java]
disabled = true
[julia]
disabled = true
[lua]
disabled = true
[nim]
disabled = true
[nodejs]
disabled = true
[ocaml]
disabled = true
[openstack]
disabled = true
[perl]
disabled = true
[php]
disabled = true
[purescript]
disabled = true
[python]
disabled = true
[ruby]
disabled = true
[rust]
disabled = true
[swift]
disabled = true
[zig]
disabled = true
